version: '3.9'

services:

  post-database:
    container_name: post-database
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: $POST_DB_HOSTNAME
    deploy:
      resources:
        limits:
          memory: 500M

  dse-studio:
    image: datastax/dse-studio
    container_name: dse-studio
    restart: always
    ports:
      - "9091:9091"
    environment:
      DS_LICENSE: accept


  dse-server:
    image: datastax/dse-server:6.7.15-ubi7
    container_name: dse-server
    restart: always
    ports:
      - "9042:9042"
    environment:
      DS_LICENSE: accept

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: -Dkeycloak.profile.feature.upload_scripts=enabled
    environment:
      # VIRTUAL_HOST: auth.dev.komsumdannehaber.com
      # VIRTUAL_PORT: 8080
      # LETSENCRYPT_HOST: auth.dev.komsumdannehaber.com
      # LETSENCRYPT_EMAIL: sessevmezbugra@gmail.com
      # PROXY_ADDRESS_FORWARDING: "true"
      # JDBC_PARAMS: "ssl=false" 
      DB_VENDOR: MYSQL
      DB_ADDR: host.docker.internal
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: 123456
      # KEYCLOAK_HTTP_PORT: 8080
      # KEYCLOAK_HOSTNAME: auth.arcloudfactories.com
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8080:8080
    depends_on:
      # - keycloak-database
      - nginx-proxy
      - geography-database #keycloak-database olarak degistirilecek

# Volumes
volumes:
  database-volume:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

#networks:
#  default:
#    external:
#      name: webproxy