version: '3.9'

services:

  geography-database:
    container_name: geography-database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $GEOGRAPHY_DB_PASSWORD
      MYSQL_USER: $GEOGRAPHY_DB_USERNAME
      MYSQL_PASSWORD: $GEOGRAPHY_DB_PASSWORD
      MYSQL_DATABASE: $GEOGRAPHY_DB_NAME
    ports:
      - "${GEOGRAPHY_DB_EXPOSED_PORT}:3306"
    restart: always
    volumes:
      - /var/lib/mysql-volume:/var/lib/mysql

  post-database:
    container_name: post-database
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: $POST_DB_HOSTNAME
    deploy:
      resources:
        limits:
          memory: 500M

  dse-studio:
    image: datastax/dse-studio
    container_name: dse-studio
    restart: always
    ports:
      - "9091:9091"
    environment:
      DS_LICENSE: accept


  dse-server:
    image: datastax/dse-server:6.7.15-ubi7
    container_name: dse-server
    restart: always
    ports:
      - "9042:9042"
    environment:
      DS_LICENSE: accept

# Volumes
volumes:
  database-volume:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:

#networks:
#  default:
#    external:
#      name: webproxy