eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  server:
    peer-node-read-timeout-ms: 300000
    
keycloak:
  auth-server-url: ${KEYCLOAK_URI:https://auth.dev.komsumdannehaber.com}/auth
  realm: komsumdannehaber
  bearer-only: true
  public-client: true
  principal-attribute: preferred_username
  ssl-required: none
  
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    restart:
      enabled: true
  