spring:
  application:
    name: feed-service
  data:
    cassandra:
      port: ${RDS_PORT:9042}
      schema-action: CREATE_IF_NOT_EXISTS
      keyspace-name: ${RDS_DB_NAME:mykeyspace}
      contact-points: ${RDS_HOSTNAME:localhost}
      entity-base-package: com.komsum.feed.entity
      data-center: ${DATA_CENTER:dc1}

server:
  port: 8093
  
  
keycloak:
  resource: feed-service
  credentials: 
    secret: 5c341f4c-10df-45f2-a028-741b35818ff3