spring:
  application:
    name: feed-service
  data:
    cassandra:
      port: ${RDS_PORT:9042}
      schema-action: CREATE_IF_NOT_EXISTS
      keyspace-name: ${RDS_DB_NAME:mykeyspace}
      contact-points: ${RDS_HOSTNAME:localhost}
      entity-base-package: com.komsum.feed.entity
      data-center: ${DATA_CENTER:dc1}

server:
  port: 8093
  
  
keycloak:
  resource: feed-service
  credentials: 
    secret: ${FEED_SERVICE_CLIENT_SECRET:5c341f4c-10df-45f2-a028-741b35818ff3}
    
springdoc:
  swagger-ui:
    oauth:
      clientId: feed-service
      clientSecret: ${FEED_SERVICE_CLIENT_SECRET:5c341f4c-10df-45f2-a028-741b35818ff3}
      usePkceWithAuthorizationCodeGrant: true
  oAuthFlow:
    authorizationUrl: ${KEYCLOAK_URI:http://localhost:8080}/auth/realms/komsumdannehaber/protocol/openid-connect/auth
    tokenUrl: ${KEYCLOAK_URI:http://localhost:8080}/auth/realms/komsumdannehaber/protocol/openid-connect/token