spring:
  application:
    name: feed-service
  data:
    cassandra:
      port: ${RDS_PORT:9042}
      schema-action: CREATE_IF_NOT_EXISTS
      keyspace-name: ${RDS_DB_NAME:mykeyspace}
      contact-points: ${RDS_HOSTNAME:localhost}
      entity-base-package: com.komsum.feed.entity
      data-center: dc1

server:
  port: 8093