spring:
  application:
    name: file-service
  datasource:
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:file}?serverTimezone=UTC
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 20MB

server:
  port: 8094
  
keycloak:
  resource: file-service
  credentials: 
    secret: ${CLIENT_SECRET:bdfc6e50-0f72-4d4a-847c-664834848bf6}
 
     
springdoc:
  swagger-ui:
    oauth:
      clientId: file-service
      clientSecret: ${CLIENT_SECRET:bdfc6e50-0f72-4d4a-847c-664834848bf6}
      usePkceWithAuthorizationCodeGrant: true
  oAuthFlow:
    authorizationUrl: ${KEYCLOAK_URI:http://localhost:8080}/auth/realms/komsumdannehaber/protocol/openid-connect/auth
    tokenUrl: ${KEYCLOAK_URI:http://localhost:8080}/auth/realms/komsumdannehaber/protocol/openid-connect/token