spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: geography-service
          uri: ${GEOGRAPHY_SERVICE_URI:http://localhost:8090}
          predicates:
            - Path=/geography/**
        - id: post-service
          uri: ${POST_SERVICE_URI:http://localhost:8091}
          predicates:
            - Path=/post/**
        - id: tag-service
          uri: ${TAG_SERVICE_URI:http://localhost:8092}
          predicates:
            - Path=/tag/**
        - id: feed-service
          uri: ${FEED_SERVICE_URI:http://localhost:8093}
          predicates:
            - Path=/feed/**
        - id: file-service
          uri: ${FILE_SERVICE_URI:http://localhost:8094}
          predicates:
            - Path=/file/**
        - id: user-service
          uri: ${USER_SERVICE_URI:http://localhost:8095}
          predicates:
            - Path=/user/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 4000
