spring:
  application:
    name: post-service
  data:
    mongodb:
      database: ${RDS_DB_NAME:post}
      host: ${RDS_HOSTNAME:localhost}
      port: ${RDS_PORT:27017}
      username: ${RDS_USERNAME:root}
      password: ${RDS_PASSWORD:example}
      authentication-database: ${RDS_ADMIN_DATABASE:admin}

server:
  port: 8091
  
  
keycloak:
  resource: post-service
  credentials: 
    secret: ${POST_SERVICE_CLIENT_SECRET:e799221d-45c7-421c-add5-054e3ba5dd1b}
    
    
springdoc:
  swagger-ui:
    oauth:
      clientId: post-service
      clientSecret: ${POST_SERVICE_CLIENT_SECRET:e799221d-45c7-421c-add5-054e3ba5dd1b}
      usePkceWithAuthorizationCodeGrant: true
  oAuthFlow:
    authorizationUrl: ${KEYCLOAK_URI:http://localhost:8080}/auth/realms/komsumdannehaber/protocol/openid-connect/auth
    tokenUrl: ${KEYCLOAK_URI:http://localhost:8080}/auth/realms/komsumdannehaber/protocol/openid-connect/token