spring:
  application:
    name: tag-service
  data:
    mongodb:
      database: ${RDS_DB_NAME:tag}
      host: ${RDS_HOSTNAME:localhost}
      port: ${RDS_PORT:27017}
      username: ${RDS_USERNAME:root}
      password: ${RDS_PASSWORD:example}
      authentication-database: ${RDS_ADMIN_DATABASE:admin}

server:
  port: 8092
  
  
keycloak:
  resource: tag-service
  credentials: 
    secret: ${CLIENT_SECRET:29f86575-f4c1-4eba-a27a-7ff3460647ad}
    
    
springdoc:
  swagger-ui:
    oauth:
      clientId: tag-service
      clientSecret: ${CLIENT_SECRET:29f86575-f4c1-4eba-a27a-7ff3460647ad}
#      usePkceWithAuthorizationCodeGrant: true
#  oAuthFlow:
#    authorizationUrl: ${KEYCLOAK_URI:http://localhost:8080}/auth/realms/komsumdannehaber/protocol/openid-connect/auth
#    tokenUrl: ${KEYCLOAK_URI:http://localhost:8080}/auth/realms/komsumdannehaber/protocol/openid-connect/token