spring:
  application:
    name: user-service
  datasource:
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:user}?serverTimezone=UTC
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:123456}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8095
  
  
keycloak:
  resource: user-service
  credentials: 
    secret: ${CLIENT_SECRET:f5032b31-d9f0-4577-8120-602b8a157306}
    
springdoc:
  swagger-ui:
    oauth:
      clientId: user-service
      clientSecret: ${CLIENT_SECRET:f5032b31-d9f0-4577-8120-602b8a157306}
      usePkceWithAuthorizationCodeGrant: true
  oAuthFlow:
    authorizationUrl: ${KEYCLOAK_URI:https://auth.dev.komsumdannehaber.com}/auth/realms/komsumdannehaber/protocol/openid-connect/auth
    tokenUrl: ${KEYCLOAK_URI:https://auth.dev.komsumdannehaber.com}/auth/realms/komsumdannehaber/protocol/openid-connect/token