apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    name: eureka-service
    app: komsum-app
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30005
  selector:
    name: eureka-service
    app: komsum-app