pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {

        stage('Build') {
            steps {
                sh 'docker run -i --rm -v "$PWD":/app -v "$HOME/.m2":/root/.m2 -w /app/file-service maven mvn clean package -DskipTests'
                sh 'cd file-service && docker build -t bsessevmez/file-service:latest .'
            }
        }
    }
}