apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  labels:
    name: config-server-service
    app: komsum-app
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30006
  selector:
    name: config-server-pod
    app: komsum-app