apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  labels:
    name: gateway-service-deployment
    app: komsum-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gateway-service-pod
      app: komsum-app
  template:
    metadata:
      name: gateway-service-pod
      labels:
        name: gateway-service-pod
        app: komsum-app
    spec:
      containers:
        - name: gateway-service
          image: bsessevmez/gateway-service:latest
          ports:
            - containerPort: 4000
          env:
          - name: CONFIG_URI
            valueFrom:
              secretKeyRef:
                name: komsum-secret
                key: CONFIG_URI
          - name: FAIL_FAST
            valueFrom:
              secretKeyRef:
                name: komsum-secret
                key: FAIL_FAST
          - name: EUREKA_URI
            valueFrom:
              secretKeyRef:
                name: komsum-secret
                key: EUREKA_URI
    