apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    name: gateway-service
    app: komsum-app
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30007
  selector:
    name: gateway-service
    app: komsum-app