pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd geography-service && docker build -t bsessevmez/geography-service:latest .'
            }
        }
    }
}