pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Maven Build') {
            agent {
                docker {
                    image 'maven:3.8.1-adoptopenjdk-11'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'cd geography-service && mvn -B -DskipTests clean package'
            }
        }
        stage('Docker Build') {
            steps {
                sh 'cd geography-service && docker build -t bsessevmez/geography-service:latest .'
            }
        }
    }
}