pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-v /root/.m2:/root/.m2'
        }
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                        cd geography-service
                        mvn -B -DskipTests clean package'
                        docker build -t bsessevmez/geography-service:latest .
                '''
            }
        }
    }
}