pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {

        stage('Build') {
            steps {
                sh 'docker run -i --rm -v "$PWD":/app -v "$HOME/.m2":/root/.m2 -w /app/user-service maven mvn clean package -DskipTests'
                sh 'cd user-service && docker build -t bsessevmez/user-service:latest .'
            }
        }
    }
}